In [1]:
print("hello")

hello


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
b=np.array([1,2,3],[4,5,6])
print(a)
print(b)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [5]:
b=np.array([(1,2,3),(4,5,6)])
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [6]:
c=np.zeros(2)

In [7]:
print(c)

[0. 0.]


In [8]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
c=np.zeros((3,2,4))

In [10]:
print(c)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [11]:
c=np.full((3,2),2)
print(c)

[[2 2]
 [2 2]
 [2 2]]


In [13]:
a=np.array([(1,2,3,4,5,6)])
np.random.rand(3,5)
print(a)

[[1 2 3 4 5 6]]


In [14]:
# a=np.array([(1,2,3,4,5,6)])
a=np.random.rand(3,5)
print(a)

[[0.48908649 0.25973825 0.44104625 0.15469189 0.15567706]
 [0.79480495 0.81997606 0.57717579 0.15784342 0.59321171]
 [0.41671963 0.61633627 0.12502754 0.02284948 0.00872334]]


In [15]:
c=np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
c=np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
d=np.copy(c)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
a.view()

array([[0.48908649, 0.25973825, 0.44104625, 0.15469189, 0.15567706],
       [0.79480495, 0.81997606, 0.57717579, 0.15784342, 0.59321171],
       [0.41671963, 0.61633627, 0.12502754, 0.02284948, 0.00872334]])

In [24]:
b1=a.reshape(5,-1)
print(b1)

[[0.48908649 0.25973825 0.44104625]
 [0.15469189 0.15567706 0.79480495]
 [0.81997606 0.57717579 0.15784342]
 [0.59321171 0.41671963 0.61633627]
 [0.12502754 0.02284948 0.00872334]]


In [28]:
f=c.sort()
f

In [31]:
c1=np.array([[1,2,7],[4,8,6]])
c1.sort(axis=1)
c1

array([[1, 2, 7],
       [4, 6, 8]])

In [32]:
a.view()

array([[0.48908649, 0.25973825, 0.44104625, 0.15469189, 0.15567706],
       [0.79480495, 0.81997606, 0.57717579, 0.15784342, 0.59321171],
       [0.41671963, 0.61633627, 0.12502754, 0.02284948, 0.00872334]])

In [33]:
z=np.delete(a,2)
z

array([0.48908649, 0.25973825, 0.15469189, 0.15567706, 0.79480495,
       0.81997606, 0.57717579, 0.15784342, 0.59321171, 0.41671963,
       0.61633627, 0.12502754, 0.02284948, 0.00872334])

In [34]:
a=[1,2,3]
a

[1, 2, 3]

In [35]:
z=np.delete(a,2)
z

array([1, 2])